In [1]:
#ipynb for Movie Recommender :)

In [2]:
import pandas as pd 
import numpy as np

In [3]:
mov = pd.read_csv("data/tmdb_5000_movies.csv")

In [4]:
cred = pd.read_csv("data/tmdb_5000_credits.csv")

In [5]:
#merging the datasets
mov = mov.merge(cred,on="title")
mov.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [6]:
mov.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [7]:
mov = mov[['movie_id','title','genres','cast','crew','keywords','vote_average']] #only essential columns
mov

,movie_id,title,genres,cast,crew,keywords,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",7.2
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",6.9
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",6.3
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",7.6
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",6.1
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",6.6
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",[],5.9
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",7.0
4807,126186,Shanghai Calling,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[],5.7
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",6.3

In [8]:
#converting stringified json into usable values
import ast #Abstract Syntax Trees
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

#mov['genres'] = mov['genres'].apply(convert)
mov['cast'] = mov['cast'].apply(convert)
mov['crew'] = mov['crew'].apply(convert)
mov

,movie_id,title,genres,cast,crew,keywords,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",7.2
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",6.9
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",6.3
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Charles Roven, Christopher Nolan...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",7.6
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Andrew Stanton, John Lasseter...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",6.1
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",6.6
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[Edward Burns, Kerry Bishé, Marsha Dietlein, C...","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",7.0
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[Daniel Hsia, Daniel Hsia]",[],5.7
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[Clark Peterson, Andrew Reimer, Brian Herzling...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",6.3

In [9]:
def convert_cast(text):
    return text[:3]
mov['cast'] = mov['cast'].apply(convert_cast)
mov

,movie_id,title,genres,cast,crew,keywords,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",7.2
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",6.9
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",6.3
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",7.6
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",6.1
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",6.6
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",7.0
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",6.3

In [15]:
#mov['genres'] = mov['genres'].apply(convert)
#mov['keywords'] = mov['keywords'].apply(convert)
mov

,movie_id,title,genres,cast,crew,keywords,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[culture clash, future, space war, space colon...",7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[ocean, drug abuse, exotic island, east india ...",6.9
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[spy, based on novel, secret agent, sequel, mi...",6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[dc comics, crime fighter, terrorist, secret i...",7.6
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[based on novel, mars, medallion, space travel...",6.1
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[united states–mexico barrier, legs, arms, pap...",6.6
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[date, love at first sight, narration, investi...",7.0
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[obsession, camcorder, crush, dream girl]",6.3

In [17]:
# addin tags 
mov['tags'] = mov['genres'] + mov['cast'] + mov['crew'] + mov['keywords']
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[culture clash, future, space war, space colon...",7.2,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[ocean, drug abuse, exotic island, east india ...",6.9,"[Adventure, Fantasy, Action, Johnny Depp, Orla..."
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[spy, based on novel, secret agent, sequel, mi...",6.3,"[Action, Adventure, Crime, Daniel Craig, Chris..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[dc comics, crime fighter, terrorist, secret i...",7.6,"[Action, Crime, Drama, Thriller, Christian Bal..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[based on novel, mars, medallion, space travel...",6.1,"[Action, Adventure, Science Fiction, Taylor Ki..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[united states–mexico barrier, legs, arms, pap...",6.6,"[Action, Crime, Thriller, Carlos Gallardo, Jai..."
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9,"[Comedy, Romance, Edward Burns, Kerry Bishé, M..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[date, love at first sight, narration, investi...",7.0,"[Comedy, Drama, Romance, TV Movie, Eric Mabius..."
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7,"[Daniel Henney, Eliza Coupe, Bill Paxton, Dani..."
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[obsession, camcorder, crush, dream girl]",6.3,"[Documentary, Drew Barrymore, Brian Herzlinger..."

In [19]:
#mov['tags'] = mov['tags'].apply(lambda x: " ".join(x)) #list to string cuz ML Models use string matching
#mov_def = mov[['movie_id','title','tags']].copy()
#mov_def['tags'] = mov_def['tags'].apply(lambda x: x.lower())
print(type(mov['tags'][0]))
mov['tags'] = mov['tags'].apply(lambda x: " ".join(x))
mov['tags'] = mov['tags'].apply(lambda x: x.lower())
#mov_def

<class 'list'>

In [20]:
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[culture clash, future, space war, space colon...",7.2,action adventure fantasy science fiction sam w...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[ocean, drug abuse, exotic island, east india ...",6.9,adventure fantasy action johnny depp orlando b...
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[spy, based on novel, secret agent, sequel, mi...",6.3,action adventure crime daniel craig christoph ...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[dc comics, crime fighter, terrorist, secret i...",7.6,action crime drama thriller christian bale mic...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[based on novel, mars, medallion, space travel...",6.1,action adventure science fiction taylor kitsch...
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[united states–mexico barrier, legs, arms, pap...",6.6,action crime thriller carlos gallardo jaime de...
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9,comedy romance edward burns kerry bishé marsha...
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[date, love at first sight, narration, investi...",7.0,comedy drama romance tv movie eric mabius kris...
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7,daniel henney eliza coupe bill paxton daniel h...
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[obsession, camcorder, crush, dream girl]",6.3,documentary drew barrymore brian herzlinger co...

In [36]:
#count vectorizer to convert string data into numbers (each movie will be a point in vector space)
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(mov_def['tags']).toarray()
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [37]:
mov_def['tags'].isnull().sum()

np.int64(0)

In [38]:
print(mov_def['tags'][0])

a       c       t       i       o       n               a       d       v       e       n       t       u       r       e               f       a       n       t       a       s       y               s       c       i       e       n       c       e               f       i       c       t       i       o       n               s       a       m               w       o       r       t       h       i       n       g       t       o       n               z       o       e               s       a       l       d       a       n       a               s       i       g       o       u       r       n       e       y               w       e       a       v       e       r               s       t       e       p       h       e       n               e       .               r       i       v       k       i       n               r       i       c       k               c       a       r       t       e       r               c       h       r       i       s       t       o       p       h       e       r               b       o       y       e       s               c       h       r       i       s       t       o       p       h       e       r               b       o       y       e       s               m       a       l       i               f       i       n       n               j       a       m       e       s               h       o       r       n       e       r               j       a       m       e       s               c       a       m       e       r       o       n               j       a       m       e       s               c       a       m       e       r       o       n               j       a       m       e       s               c       a       m       e       r       o       n               j       a       m       e       s               c       a       m       e       r       o       n               j       a       m       e       s               c       a       m       e       r       o       n               a       n       d       r       e       w               m       e       n       z       i       e       s               j       i       l       l               b       r       o       o       k       s               m       a       r       g       e       r       y               s       i       m       k       i       n               k       e       v       i       n               i       s       h       i       o       k       a               d       i       c       k               b       e       r       n       s       t       e       i       n               s       h       a       n       n       o       n               m       i       l       l       s               d       e       n       n       i       e               t       h       o       r       p       e               j       a       n       a               v       a       n       c       e               d       e       b       o       r       a       h               l       y       n       n               s       c       o       t       t               j       o       n               l       a       n       d       a       u               s       e       a       n               h       a       w       o       r       t       h               k       i       m               s       i       n       c       l       a       i       r               k       i       m               s       i       n       c       l       a       i       r               r       i       c       h       a       r       d               f       .               m       a       y       s               l       a       e       t       a               k       a       l       o       g       r       i       d       i       s               m       a       y       e       s               c       .               r       u       b       e       o               m       a       u       r       o               f       i       o       r       e               s       c       o       t       t               h       e       r       b       e       r       t       s       o       n               w       o       o       d       y               s       c       h       u       l       t       z               l       i       n       d       a               d       e       v       e       t       t       a               l       i       n       d       a               d       e       v       e       t       t       a               r       i       c       h       a       r       d               b       l       u       c       k               s       i       m       o       n               b       r       i       g       h       t               r       i       c       h       a       r       d               m       a       r       t       i       n               s       t       e       v       e               r       .               m       o       o       r       e               j       o       h       n               r       e       f       o       u       a               k       a       r       l               j       .               m       a       r       t       i       n               c       h       i       l       i       n       g               l       i       n               i       l       r       a       m               c       h       o       i               s       t       e       v       e       n               q       u       a       l       e               c       a       r       l       a               m       e       y       e       r               n       i       c       k               b       a       s       s       e       t       t               j       i       l       l               c       o       r       m       a       c       k               a       n       d       y               m       c       l       a       r       e       n               t       e       r       r       y               n       o       t       a       r       y               g       a       r       r       e       t       t               w       a       r       r       e       n               j       o       n       a       t       h       a       n               r       o       t       h       b       a       r       t               s       t       e       f       a       n               d       e       c       h       a       n       t               t       o       d       d               c       h       e       r       n       i       a       w       s       k       y               m       i       r       a       n       d       a               r       i       v       e       r       s               r       o       b       e       r       t               s       t       r       o       m       b       e       r       g               j       o       h       n               h       a       r       d       i       n       g               r       o       b       e       r       t       o               d       e               a       n       g       e       l       i       s               m       i       k       e               s       m       i       t       h       s       o       n               a       l       a       i       n               l       a       l       a       n       n       e               l       u       c       a       s               s       a       l       t       o       n               j       a       n       a       c       e               t       a       s       h       j       i       a       n               s       t       e       p       h       e       n               r       o       s       e       n       b       a       u       m               f       r       a       n       k       i       e               k       a       r       e       n       a               l       i       s       a               l       o       v       a       a       s               j       o       n       a       t       h       a       n               f       a       w       k       n       e       r               r       o       b       e       r       t               b       a       v       i       n               a       n       t       h       o       n       y               a       l       m       a       r       a       z               c       a       r       o       l       y       n               m       .               f       e       n       t       o       n               b       e       t       h               k       o       e       n       i       g       s       b       e       r       g               s       a       m               p       a       g       e               t       e       x               k       a       d       o       n       a       g       a               k       i       m               f       o       s       c       a       t       o               t       a       m       m       y               s       .               l       e       e               d       e       n       n       y               c       a       i       r       a               j       a       m       e       s               w       a       i       t       k       u       s               a       d       d       i       s       o       n               t       e       a       g       u       e               c       .               s       c       o       t       t               b       a       k       e       r               l       u       k       e               c       a       s       k       a               d       a       v       i       d               c       h       o       w               j       o       n       a       t       h       a       n               d       y       e       r               j       o       s       e       p       h               h       i       u       r       a               r       e       b       e       c       c       a               j       e       l       l       i       e               r       o       b       e       r       t               a       n       d       r       e       w               j       o       h       n       s       o       n               m       i       k       e               s       t       a       s       s       i               j       o       h       n               v       i       l       l       a       r       i       n       o               j       e       f       f       r       e       y               w       i       s       n       i       e       w       s       k       i               c       h       e       r       y       l               n       a       r       d       i               m       a       r       s       h       a       l       l               w       i       n       n               g       w       e       n       d       o       l       y       n               y       a       t       e       s               w       h       i       t       t       l       e               w       i       l       l       i       a       m               s       t       e       i       n               l       u       l       a               w       a       s       h       i       n       g       t       o       n               c       h       r       i       s               d       e       l               c       o       n       t       e               r       .               c       h       r       i       s       t       o       p       h       e       r               w       h       i       t       e               d       a       n               l       e       m       m       o       n               t       i       m               n       i       e       l       s       e       n               m       i       c       h       a       e       l               m       u       l       h       o       l       l       a       n       d               t       h       o       m       a       s               n       i       t       t       m       a       n       n               e       d       s       o       n               w       i       l       l       i       a       m       s               c       h       r       i       s       t       i       n       e               c       a       r       r               j       o       h       n               b       r       u       n       o               d       a       v       i       d               e       m       m       e       r       i       c       h       s               c       h       r       i       s       t       o       p       h       e       r               s       c       a       r       a       b       o       s       i       o               j       e       n       n       i       f       e       r               t       e       v       e       s               b       r       i       g       i       t       t       e               y       o       r       k       e               k       e       n               f       i       s       c       h       e       r               i       a       i       n               h       u       t       t       o       n               s       t       e       v       e               i       n       g       r       a       m               j       o       y       c       e               c       o       x               j       e       n       n       y               f       o       s       t       e       r               c       h       r       i       s       t       o       p       h       e       r               m       a       r       i       n       o               j       i       m               m       i       l       t       o       n               c       y       n       d       i               o       c       h       s               l       u       c       a       s               p       u       t       n       a       m               a       n       t       h       o       n       y               '       m       a       x       '               i       v       i       n       s               j       o       h       n               k       n       o       l       l               e       r       i       c               s       a       i       n       d       o       n               w       a       y       n       e               s       t       a       b       l       e       s               d       a       v       i       d               s       t       i       n       n       e       t       t               g       u       y               w       i       l       l       i       a       m       s               s       t       u       a       r       t               t       h       o       r       p               g       i       l       e       s               c       o       b       u       r       n               m       a       r       k               f       e       l       l       m       a       n               s       c       o       t       t               s       p       r       a       g       u       e               j       e       r       e       m       y               h       o       l       l       o       b       o       n               o       r       l       a       n       d       o               m       e       u       n       i       e       r               t       a       i       s       u       k       e               t       a       n       i       m       u       r       a               l       i       l       i       a               m       i       s       h       e       l               a       c       e       v       e       d       o               a       l       e       j       a       n       d       r       o               m       .               h       e       r       n       a       n       d       e       z               m       a       r       v       i       n               h       a       l       l               j       u       d       y               a       l       l       e       y               m       i       k       e               p       e       r       r       y               a       n       d       r       e       w               m       o       r       l       e       y               s       e       t       h               e       n       g       s       t       r       o       m               e       r       i       c               o       l       i       v       e       r               m       a       t       s       u       n       e               s       u       z       u       k       i               p       a       u       l               t       o       b       i       n               r       o       x       a       n       e               g       r       i       f       f       i       n               a       r       u       n               r       a       m       -       m       o       h       a       n               g       e       o       r       g       i       a               l       o       c       k       h       a       r       t       -       a       d       a       m       s               t       h       r       a       i       n               s       h       a       d       b       o       l       t               b       r       a       d               a       l       e       x       a       n       d       e       r               s       h       a       d       i               a       l       m       a       s       s       i       z       a       d       e       h               s       i       m       o       n               c       l       u       t       t       e       r       b       u       c       k               g       r       a       e       m       e               d       e       m       m       o       c       k       s               a       d       r       i       a       n               f       e       r       n       a       n       d       e       s               m       i       t       c       h               g       a       t       e       s               j       e       r       r       y               k       u       n       g               a       n       d       y               l       o       m       a       s               s       e       b       a       s       t       i       a       n               m       a       r       i       n       o               m       a       t       t       h       i       a       s               m       e       n       z               s       e       r       g       e       i               n       e       v       s       h       u       p       o       v               p       h       i       l       i       p       p       e               r       e       b       o       u       r       s               m       i       c       h       a       e       l               t       a       k       a       r       a       n       g       i               d       a       v       i       d               w       e       i       t       z       b       e       r       g               b       e       n               w       h       i       t       e               m       i       n               w       i       n       d       l       e               c       u       l       t       u       r       e               c       l       a       s       h               f       u       t       u       r       e               s       p       a       c       e               w       a       r               s       p       a       c       e               c       o       l       o       n       y               s       o       c       i       e       t       y               s       p       a       c       e               t       r       a       v       e       l               f       u       t       u       r       i       s       t       i       c               r       o       m       a       n       c       e               s       p       a       c       e               a       l       i       e       n               t       r       i       b       e               a       l       i       e       n               p       l       a       n       e       t               c       g       i               m       a       r       i       n       e               s       o       l       d       i       e       r               b       a       t       t       l       e               l       o       v       e               a       f       f       a       i       r               a       n       t       i               w       a       r               p       o       w       e       r               r       e       l       a       t       i       o       n       s               m       i       n       d               a       n       d       