In [1]:
#ipynb for Movie Recommender :)

In [2]:
import pandas as pd 
import numpy as np

In [3]:
mov = pd.read_csv("data/tmdb_5000_movies.csv")

In [4]:
cred = pd.read_csv("data/tmdb_5000_credits.csv")

In [5]:
#merging the datasets
mov = mov.merge(cred,on="title")
mov.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [6]:
mov.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [7]:
mov = mov[['movie_id','title','genres','cast','crew','keywords','vote_average','overview']] #only essential columns
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,overview
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",7.2,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",6.9,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",6.3,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",7.6,Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",6.1,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",6.6,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",[],5.9,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",7.0,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[],5.7,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",6.3,Ever since the second grade when he first saw ...

In [8]:
#converting stringified json into usable values
import ast #Abstract Syntax Trees
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

mov['genres'] = mov['genres'].apply(convert)
mov['cast'] = mov['cast'].apply(convert)
mov['crew'] = mov['crew'].apply(convert)
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",7.2,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",6.9,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",6.3,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Charles Roven, Christopher Nolan...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",7.6,Following the death of District Attorney Harve...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Andrew Stanton, John Lasseter...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",6.1,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",6.6,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein, C...","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",7.0,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[Daniel Hsia, Daniel Hsia]",[],5.7,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[Clark Peterson, Andrew Reimer, Brian Herzling...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",6.3,Ever since the second grade when he first saw ...

In [9]:
def convert_cast(text):
    return text[:3]
mov['cast'] = mov['cast'].apply(convert_cast)
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",7.2,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",6.9,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",6.3,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",7.6,Following the death of District Attorney Harve...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",6.1,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",6.6,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",7.0,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",6.3,Ever since the second grade when he first saw ...

In [10]:
#mov['genres'] = mov['genres'].apply(convert)
mov['keywords'] = mov['keywords'].apply(convert)
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[culture clash, future, space war, space colon...",7.2,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[ocean, drug abuse, exotic island, east india ...",6.9,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[spy, based on novel, secret agent, sequel, mi...",6.3,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[dc comics, crime fighter, terrorist, secret i...",7.6,Following the death of District Attorney Harve...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[based on novel, mars, medallion, space travel...",6.1,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[united states–mexico barrier, legs, arms, pap...",6.6,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[date, love at first sight, narration, investi...",7.0,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[obsession, camcorder, crush, dream girl]",6.3,Ever since the second grade when he first saw ...

In [11]:
# addin tags 
mov['tags'] = mov['genres'] + mov['cast'] + mov['crew'] + mov['keywords']
mov

,movie_id,title,genres,cast,crew,keywords,vote_average,overview,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...","[culture clash, future, space war, space colon...",7.2,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[ocean, drug abuse, exotic island, east india ...",6.9,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action, Johnny Depp, Orla..."
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[spy, based on novel, secret agent, sequel, mi...",6.3,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime, Daniel Craig, Chris..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan...","[dc comics, crime fighter, terrorist, secret i...",7.6,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller, Christian Bal..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter...","[based on novel, mars, medallion, space travel...",6.1,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction, Taylor Ki..."
...,...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[Robert Rodriguez, Robert Rodriguez, Robert Ro...","[united states–mexico barrier, legs, arms, pap...",6.6,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller, Carlos Gallardo, Jai..."
4805,72766,Newlyweds,"[Comedy, Romance]","[Edward Burns, Kerry Bishé, Marsha Dietlein]","[Edward Burns, Edward Burns, Edward Burns, Wil...",[],5.9,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance, Edward Burns, Kerry Bishé, M..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[Eric Mabius, Kristin Booth, Crystal Lowe]","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M...","[date, love at first sight, narration, investi...",7.0,"""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie, Eric Mabius..."
4807,126186,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[Daniel Hsia, Daniel Hsia]",[],5.7,When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton, Dani..."
4808,25975,My Date with Drew,[Documentary],"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Clark Peterson, Andrew Reimer, Brian Herzling...","[obsession, camcorder, crush, dream girl]",6.3,Ever since the second grade when he first saw ...,"[Documentary, Drew Barrymore, Brian Herzlinger..."

In [12]:
#mov['tags'] = mov['tags'].apply(lambda x: " ".join(x)) #list to string cuz ML Models use string matching
#mov_def = mov[['movie_id','title','tags']].copy()
#mov_def['tags'] = mov_def['tags'].apply(lambda x: x.lower())
print(type(mov['tags'][0]))
mov['tags'] = mov['tags'].apply(lambda x: " ".join(x))
mov['tags'] = mov['tags'].apply(lambda x: x.lower())
#mov_def

<class 'list'>

In [13]:
mov_def = mov[['movie_id','title','tags']].copy()
mov_def

,movie_id,title,tags
0,19995,Avatar,action adventure fantasy science fiction sam w...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action johnny depp orlando b...
2,206647,Spectre,action adventure crime daniel craig christoph ...
3,49026,The Dark Knight Rises,action crime drama thriller christian bale mic...
4,49529,John Carter,action adventure science fiction taylor kitsch...
...,...,...,...
4804,9367,El Mariachi,action crime thriller carlos gallardo jaime de...
4805,72766,Newlyweds,comedy romance edward burns kerry bishé marsha...
4806,231617,"Signed, Sealed, Delivered",comedy drama romance tv movie eric mabius kris...
4807,126186,Shanghai Calling,daniel henney eliza coupe bill paxton daniel h...
4808,25975,My Date with Drew,documentary drew barrymore brian herzlinger co...

In [14]:
#count vectorizer to convert string data into numbers (each movie will be a point in vector space) *imp*
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(mov_def['tags']).toarray()
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [15]:
import pickle

pickle.dump(mov, open('movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))